info:
  contact: {}
paths:
  /v1/images/:
    get:
      consumes:
      - multipart/form-data
      description: Download an image file (JPEG/PNG).
      parameters:
      - description: Offset of images to fetch
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download an image
    post:
      consumes:
      - multipart/form-data
      description: Upload an image file (JPEG/PNG).
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - text/plain
      responses:
        "200":
          description: File uploaded successfully!
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload an image
swagger: "2.0"
